"""
export.py -- emit the frozen quantized MLP as a C header for the RP2040 firmware.

  PYTHONPATH=. python3 compiler/export.py   ->   fw/mnist_weights.h
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from model import mlp_ref

OUT = Path(__file__).resolve().parents[1] / "fw" / "mnist_weights.h"


def _emit_i8(name, arr, f):
    flat = np.asarray(arr).astype(np.int8).ravel()
    f.write(f"static const int8_t {name}[{flat.size}] = {{")
    f.write(",".join(str(int(v)) for v in flat))
    f.write("};\n")


def _emit_i16(name, arr, f):
    flat = np.asarray(arr).astype(np.int64).ravel()
    f.write(f"static const int16_t {name}[{flat.size}] = {{")
    f.write(",".join(str(int(v)) for v in flat))
    f.write("};\n")


def main() -> int:
    p = mlp_ref.load_params()
    H = int(p["hidden"])
    with open(OUT, "w") as f:
        f.write("// Auto-generated by compiler/export.py from model/mnist/mnist_int8.npz.\n")
        f.write("// Frozen INT8 weights for the 8x8 MNIST MLP demo. Do not edit by hand.\n")
        f.write("#ifndef TENSORTILE_MNIST_WEIGHTS_H\n#define TENSORTILE_MNIST_WEIGHTS_H\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define TT_IN_DIM   64\n#define TT_HIDDEN   {H}\n#define TT_OUT_DIM  10\n")
        f.write(f"#define TT_IN_SHIFT {int(p['in_shift'])}\n")
        f.write(f"#define TT_SHIFT1   {int(p['shift1'])}\n#define TT_SHIFT2   {int(p['shift2'])}\n\n")
        _emit_i8("tt_w1", p["W1"], f)   # (H, 64) row-major
        _emit_i16("tt_b1", p["b1"], f)  # (H,)
        _emit_i8("tt_w2", p["W2"], f)   # (10, H)
        _emit_i16("tt_b2", p["b2"], f)  # (10,)
        f.write("\n#endif\n")
    print(f"wrote {OUT} (hidden={H}, shift1={int(p['shift1'])}, shift2={int(p['shift2'])})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
